import type { DashboardLinkItem } from "@/features/dashboard-links/lib/dashboard-link-catalog";

export const USTC_STUDENT_SERVICE_LINKS: DashboardLinkItem[] = [
  {
    slug: "student-services",
    title: "学工一体化",
    url: "https://xgyth.ustc.edu.cn/",
    description: "学工事务统一办理入口。",
    category: "services",
    icon: "building",
  },
  {
    slug: "ot-club",
    title: "蜗壳学社",
    url: "https://ot.ustc.edu.cn/",
    description: "校园社群与交流。",
    category: "community",
    icon: "users",
  },
  {
    slug: "study-space-booking",
    title: "学习空间预约",
    url: "https://lib.ustc.edu.cn/%e5%9b%be%e4%b9%a6%e9%a6%86%e7%a0%94%e4%bf%ae%e9%97%b4%e9%a2%84%e7%ba%a6%e7%b3%bb%e7%bb%9f/",
    description: "图书馆学习空间预约。",
    category: "academic",
    icon: "book-open",
  },
  {
    slug: "cmet-room-booking",
    title: "中区研修室预约",
    url: "http://roombooking.cmet.ustc.edu.cn/",
    description: "中区研修室预约系统。",
    category: "academic",
    icon: "building",
  },
  {
    slug: "dawu-tools",
    title: "大雾实验工具",
    url: "https://dawu.feixu.site/",
    description: "实验相关辅助工具。",
    category: "academic",
    icon: "monitor-play",
  },
  {
    slug: "physics-lab-3",
    title: "大物实验 3",
    url: "https://pems.ustc.edu.cn/",
    description: "大学物理实验平台入口。",
    category: "academic",
    icon: "book-open",
  },
  {
    slug: "history-culture",
    title: "历史文化",
    url: "http://lswhw.ustc.edu.cn/",
    description: "校园历史与文化资源。",
    category: "campus",
    icon: "school",
  },
  {
    slug: "bbs",
    title: "瀚海星云",
    url: "https://bbs.ustc.edu.cn/",
    description: "校园论坛社区。",
    category: "community",
    icon: "users",
  },
  {
    slug: "confession-wall",
    title: "表白墙",
    url: "http://www.ustcbbq.com/",
    description: "校园匿名交流平台。",
    category: "community",
    icon: "users",
  },
  {
    slug: "campus-portal",
    title: "校园信息门户",
    url: "https://i.ustc.edu.cn/",
    description: "校园信息统一门户。",
    category: "services",
    icon: "building",
  },
  {
    slug: "personal-homepage",
    title: "个人 FTP 主页",
    url: "http://home.ustc.edu.cn/",
    description: "个人主页服务入口。",
    category: "services",
    icon: "building",
  },
  {
    slug: "rec",
    title: "睿客网",
    url: "https://rec.ustc.edu.cn/",
    description: "校园资源与服务入口。",
    category: "campus",
    icon: "school",
  },
  {
    slug: "ecard",
    title: "一卡通管理",
    url: "https://ecard.ustc.edu.cn/",
    description: "校园一卡通服务。",
    category: "services",
    icon: "mail",
  },
  {
    slug: "admission-rain",
    title: "Admission Rain",
    url: "https://adrain.ustclug.org/",
    description: "招生相关信息聚合。",
    category: "campus",
    icon: "graduation-cap",
  },
  {
    slug: "licensed-software",
    title: "正版软件",
    url: "https://zbh.ustc.edu.cn/",
    description: "校内正版软件服务。",
    category: "services",
    icon: "monitor-play",
  },
  {
    slug: "print-service",
    title: "自助打印复印",
    url: "https://weixinprinthost.woquyun.com/wq-web/",
    description: "打印复印自助服务。",
    category: "services",
    icon: "clipboard-list",
  },
];
