import type { DashboardLinkItem } from "@/features/dashboard-links/lib/dashboard-link-catalog";

export const USTC_ESSENTIAL_LINKS: DashboardLinkItem[] = [
  {
    slug: "jw",
    title: "教务系统",
    url: "https://jw.ustc.edu.cn/",
    description: "选课、成绩与教学事务。",
    category: "academic",
    icon: "clipboard-list",
  },
  {
    slug: "icourse",
    title: "评课社区",
    url: "https://icourse.club/",
    description: "课程评价与经验分享。",
    category: "community",
    icon: "users",
  },
  {
    slug: "mail",
    title: "邮箱",
    url: "https://mail.ustc.edu.cn/",
    description: "USTC 邮件系统。",
    category: "services",
    icon: "mail",
  },
  {
    slug: "library",
    title: "图书馆",
    url: "http://lib.ustc.edu.cn/",
    description: "图书检索与数据库资源。",
    category: "academic",
    icon: "book-open",
  },
  {
    slug: "official",
    title: "科大官网",
    url: "https://www.ustc.edu.cn/",
    description: "学校新闻与公告。",
    category: "campus",
    icon: "school",
  },
  {
    slug: "course-platform",
    title: "网络教学平台",
    url: "https://course.ustc.edu.cn/portal",
    description: "课程资料与在线学习。",
    category: "academic",
    icon: "monitor-play",
  },
  {
    slug: "education-office",
    title: "教务处",
    url: "https://www.teach.ustc.edu.cn/",
    description: "教学管理与通知。",
    category: "services",
    icon: "graduation-cap",
  },
  {
    slug: "nan7",
    title: "南七集市",
    url: "https://nan7market.com/",
    description: "校园社区信息平台。",
    category: "community",
    icon: "building",
  },
  {
    slug: "network",
    title: "网络通",
    url: "http://wlt.ustc.edu.cn/",
    description: "网络服务与套餐办理。",
    category: "services",
    icon: "network",
  },
  {
    slug: "staff-homepage",
    title: "教工 FTP 主页",
    url: "http://staff.ustc.edu.cn/",
    description: "教工主页与相关入口。",
    category: "services",
    icon: "building",
  },
  {
    slug: "legacy-jw",
    title: "旧版教务系统",
    url: "https://mis.teach.ustc.edu.cn/",
    description: "历史教务系统入口。",
    category: "academic",
    icon: "clipboard-list",
  },
  {
    slug: "physics-lab-1",
    title: "大物实验 1",
    url: "https://jxzy.ustc.edu.cn/",
    description: "大学物理实验平台入口。",
    category: "academic",
    icon: "book-open",
  },
  {
    slug: "catalog-query",
    title: "公共查询",
    url: "https://catalog.ustc.edu.cn/query",
    description: "校内公共信息查询。",
    category: "services",
    icon: "clipboard-list",
  },
  {
    slug: "ta-management",
    title: "助教管理系统",
    url: "https://tam.cmet.ustc.edu.cn/",
    description: "助教任务与流程管理。",
    category: "academic",
    icon: "graduation-cap",
  },
  {
    slug: "physics-lab-2",
    title: "大物实验 2",
    url: "http://etis.ustc.edu.cn/",
    description: "大学物理实验平台入口。",
    category: "academic",
    icon: "book-open",
  },
];
