import type { DashboardLinkItem } from "@/features/dashboard-links/lib/dashboard-link-catalog";

export const USTC_CAMPUS_COMMUNITY_LINKS: DashboardLinkItem[] = [
  {
    slug: "second-classroom",
    title: "第二课堂",
    url: "https://young.ustc.edu.cn/login",
    description: "第二课堂活动平台。",
    category: "campus",
    icon: "school",
  },
  {
    slug: "n7-teahouse",
    title: "南七茶馆",
    url: "https://ustcforum.com/",
    description: "校园论坛交流社区。",
    category: "community",
    icon: "users",
  },
  {
    slug: "flyer",
    title: "飞跃网站",
    url: "https://ustcflyer.com/",
    description: "学习与留学信息社区。",
    category: "community",
    icon: "users",
  },
  {
    slug: "qq-proof",
    title: "QQ 号证明",
    url: "https://qq.ustc.life/",
    description: "USTC 身份关联证明。",
    category: "services",
    icon: "clipboard-list",
  },
  {
    slug: "cloud-drive",
    title: "科大云盘",
    url: "https://pan.ustc.edu.cn/",
    description: "校内云盘与文件共享。",
    category: "services",
    icon: "network",
  },
  {
    slug: "web-vpn",
    title: "Web VPN",
    url: "https://wvpn.ustc.edu.cn/",
    description: "校外访问校内资源。",
    category: "services",
    icon: "network",
  },
  {
    slug: "mirrors",
    title: "开源软件镜像",
    url: "https://mirrors.ustc.edu.cn/",
    description: "开源软件镜像下载。",
    category: "services",
    icon: "network",
  },
  {
    slug: "scc-gitlab",
    title: "SCC GitLab",
    url: "https://git.ustc.edu.cn/",
    description: "校内代码托管服务。",
    category: "services",
    icon: "monitor-play",
  },
  {
    slug: "lug-gitlab",
    title: "LUG GitLab",
    url: "https://git.lug.ustc.edu.cn/",
    description: "LUG 社区代码托管。",
    category: "community",
    icon: "monitor-play",
  },
  {
    slug: "ustc-latex",
    title: "USTC LaTeX",
    url: "https://latex.ustc.edu.cn/",
    description: "LaTeX 在线编辑与模板。",
    category: "academic",
    icon: "book-open",
  },
  {
    slug: "vlab",
    title: "Vlab",
    url: "https://vlab.ustc.edu.cn/",
    description: "虚拟实验教学平台。",
    category: "academic",
    icon: "monitor-play",
  },
  {
    slug: "classroom-2",
    title: "二教",
    url: "http://bigscreen.cmet.ustc.edu.cn/#/2",
    description: "二教教室信息大屏。",
    category: "campus",
    icon: "building",
  },
  {
    slug: "classroom-3",
    title: "三教",
    url: "http://bigscreen.cmet.ustc.edu.cn/#/3",
    description: "三教教室信息大屏。",
    category: "campus",
    icon: "building",
  },
  {
    slug: "classroom-5",
    title: "五教",
    url: "http://bigscreen.cmet.ustc.edu.cn/#/5",
    description: "五教教室信息大屏。",
    category: "campus",
    icon: "building",
  },
  {
    slug: "zhihu",
    title: "知乎",
    url: "https://www.zhihu.com/",
    description: "问答与知识社区。",
    category: "community",
    icon: "users",
  },
  {
    slug: "bilibili",
    title: "bilibili",
    url: "https://www.bilibili.com/",
    description: "视频与学习内容平台。",
    category: "community",
    icon: "users",
  },
  {
    slug: "weibo",
    title: "微博",
    url: "https://www.weibo.com/",
    description: "社交媒体与资讯平台。",
    category: "community",
    icon: "users",
  },
];
