import type { DashboardLinkItem } from "@/features/dashboard-links/lib/dashboard-link-catalog";

export const USTC_GRADUATE_AND_SUPPORT_LINKS: DashboardLinkItem[] = [
  {
    slug: "grad-service-platform",
    title: "综合服务平台",
    url: "https://yjs1.ustc.edu.cn/",
    description: "研究生综合事务平台。",
    category: "academic",
    icon: "graduation-cap",
  },
  {
    slug: "epc-platform",
    title: "EPC 平台",
    url: "https://epc.ustc.edu.cn/main.asp",
    description: "研究生培养过程平台。",
    category: "academic",
    icon: "graduation-cap",
  },
  {
    slug: "gradschool",
    title: "研究生院网站",
    url: "https://gradschool.ustc.edu.cn/",
    description: "研究生院官方站点。",
    category: "academic",
    icon: "school",
  },
  {
    slug: "study-guidance",
    title: "学业指导中心",
    url: "http://202.38.65.52/xyzd/",
    description: "学业咨询与支持服务。",
    category: "academic",
    icon: "graduation-cap",
  },
  {
    slug: "campus-wiki",
    title: "校园百科",
    url: "https://baike.ustc.edu.cn/",
    description: "校园知识百科。",
    category: "campus",
    icon: "school",
  },
  {
    slug: "hpc-center",
    title: "超算中心",
    url: "https://scc.ustc.edu.cn/",
    description: "高性能计算资源入口。",
    category: "services",
    icon: "network",
  },
  {
    slug: "payment-system",
    title: "网上缴费系统",
    url: "https://sf.ustc.edu.cn/",
    description: "校内缴费服务平台。",
    category: "services",
    icon: "mail",
  },
  {
    slug: "hospital",
    title: "校医院",
    url: "https://hospital.ustc.edu.cn/",
    description: "校医院与医疗服务。",
    category: "campus",
    icon: "building",
  },
  {
    slug: "transcript-verify",
    title: "成绩单打印",
    url: "https://verify-transcript.cmet.ustc.edu.cn/manager.action",
    description: "成绩单打印与验证。",
    category: "academic",
    icon: "clipboard-list",
  },
  {
    slug: "welcome",
    title: "迎新网",
    url: "https://welcome.ustc.edu.cn/",
    description: "新生报到与迎新信息。",
    category: "campus",
    icon: "school",
  },
  {
    slug: "admissions-office",
    title: "招生办",
    url: "https://zsb.ustc.edu.cn/",
    description: "招生政策与通知。",
    category: "campus",
    icon: "graduation-cap",
  },
  {
    slug: "equipment-repair",
    title: "教学设备报修",
    url: "https://fix.ustc.edu.cn/",
    description: "教学设备故障报修。",
    category: "services",
    icon: "clipboard-list",
  },
];
