import type { CalendarView } from "@/features/dashboard/lib/calendar";
import type {
  AnonymousDashboardData,
  AnonymousLinkGroup,
  CalendarData,
  DashboardLinkItem,
  ExamRow,
  ExamView,
  HomeworkFilter,
  HomeworkItem,
  HomeworkView,
  LinkView,
  MatchedSection,
  SignedDashboardData,
  SignedLinkGroup,
  TodoFilter,
  TodoItem,
  TodoView,
} from "@/features/dashboard/lib/dashboard-controller-helpers";
import { dashboardTabHref } from "@/features/dashboard/lib/dashboard-nav";
import type { ExamFilter } from "@/features/dashboard/lib/exams";

export function createDashboardControllerDefaultState() {
  return {
    anonymousData: null as AnonymousDashboardData | null,
    anonymousLinkGroups: [] as AnonymousLinkGroup[],
    bulkImportError: "",
    bulkImportMessage: "",
    bulkImportSemesterId: "",
    bulkImportText: "",
    calendarCopyError: "",
    calendarCopyMessage: "",
    calendarData: null as CalendarData | null,
    calendarMonth: "",
    calendarSemesterId: null as number | null,
    calendarView: "semester" as CalendarView,
    calendarWeekStart: "",
    createHomeworkAdvancedOpen: false,
    createHomeworkError: "",
    createHomeworkPublishedAt: "",
    createHomeworkSectionId: "",
    createHomeworkSubmissionDueAt: "",
    createHomeworkSubmissionStartAt: "",
    createTodoError: "",
    dashboardLinkItems: [] as DashboardLinkItem[],
    editTodoError: "",
    editingTodo: null as TodoItem | null,
    examFilter: "incomplete" as ExamFilter,
    examRows: [] as ExamRow[],
    examView: "cards" as ExamView,
    filteredExamRows: [] as ExamRow[],
    filteredTodos: [] as TodoItem[],
    homeworkFilter: "incomplete" as HomeworkFilter,
    homeworkItems: [] as HomeworkItem[],
    homeworkReferenceDate: new Date(),
    homeworkSavingById: {} as Record<string, boolean>,
    homeworkView: "cards" as HomeworkView,
    isBulkImportOpen: false,
    isConfirmImportOpen: false,
    isCreatingHomework: false,
    isCreatingTodo: false,
    isImportingSections: false,
    isMatchingSections: false,
    isUpdatingTodo: false,
    linkActionError: "",
    linkReturnTo: dashboardTabHref("links"),
    linkSearchInput: null as HTMLInputElement | null,
    linkSearchQuery: "",
    linkView: "grid" as LinkView,
    matchedSections: [] as MatchedSection[],
    overviewLinkItems: [] as DashboardLinkItem[],
    pendingRemoveSectionId: null as number | null,
    removingSectionId: null as number | null,
    selectedHomework: null as HomeworkItem | null,
    selectedImportSectionIds: [] as number[],
    selectedTodo: null as TodoItem | null,
    showCreateHomework: false,
    showCreateTodo: false,
    signedData: null as SignedDashboardData | null,
    signedLinkGroups: [] as SignedLinkGroup[],
    subscriptionActionError: "",
    subscriptionActionMessage: "",
    todoActionError: "",
    todoFilter: "incomplete" as TodoFilter,
    todoItems: [] as TodoItem[],
    todoSavingById: {} as Record<string, boolean>,
    todoView: "cards" as TodoView,
    unmatchedSectionCodes: [] as string[],
    updatingDashboardLinkSlug: null as string | null,
  };
}
