/**
 * Custom OpenAPI TypeScript type generator replacing openapi-typescript.
 *
 * Reads public/openapi.generated.json and generates a minimal TypeScript
 * compatibility shim at src/generated/openapi.ts.
 *
 * Since the API client now uses generic types rather than path-based inference,
 * this file is no longer required by callers. It is kept for documentation and
 * potential tooling use.
 */

import { readFile, writeFile } from "node:fs/promises";
import * as path from "node:path";

const ROOT = new URL("..", import.meta.url).pathname;

type OpenApiDocument = {
  paths?: Record<string, Record<string, { operationId?: string }>>;
};

function sanitizeOperationId(operationId: string): string {
  return operationId.replace(/[^a-zA-Z0-9_$]/g, "_");
}

async function main() {
  const inputPath = path.join(ROOT, "public/openapi.generated.json");
  const outputPath = path.join(ROOT, "src/generated/openapi.ts");

  const raw = await readFile(inputPath, "utf8");
  const doc = JSON.parse(raw) as OpenApiDocument;

  const paths = doc.paths ?? {};
  const pathKeys = Object.keys(paths);

  const lines: string[] = [
    "/**",
    " * This file was auto-generated by tools/generate-openapi-types.ts.",
    " * Do not make direct changes to the file.",
    " *",
    " * NOTE: The API client (src/lib/api/client.ts) uses generic types and no longer",
    " * requires path-based type inference from this file. This shim is kept for",
    " * documentation and potential tooling use.",
    " */",
    "",
    "// Placeholder types — callers should use explicit generic parameters on apiClient.",
    "export type paths = {",
  ];

  for (const apiPath of pathKeys) {
    const pathItem = paths[apiPath];
    const methods = Object.keys(pathItem).filter((m) =>
      ["get", "post", "put", "patch", "delete", "head", "options"].includes(m),
    );

    lines.push(`  ${JSON.stringify(apiPath)}: {`);
    lines.push(
      "    parameters: { query?: never; header?: never; path?: never; cookie?: never };",
    );

    for (const method of methods) {
      const op = pathItem[method];
      const opId = op.operationId
        ? sanitizeOperationId(op.operationId)
        : `${method}_${apiPath.replace(/[^a-zA-Z0-9]/g, "_")}`;
      lines.push(`    ${method}: operations[${JSON.stringify(opId)}];`);
    }

    const unusedMethods = [
      "get",
      "post",
      "put",
      "patch",
      "delete",
      "head",
      "options",
    ].filter((m) => !methods.includes(m));
    for (const m of unusedMethods) {
      lines.push(`    ${m}?: never;`);
    }

    lines.push("  };");
  }

  lines.push("};", "", "export type operations = Record<string, unknown>;", "");

  await writeFile(outputPath, lines.join("\n"), "utf8");
  console.log(`Generated type shim with ${pathKeys.length} paths.`);
  console.log(`Written to ${outputPath}`);
}

await main();
