name: Release

on:
  push:
    branches:
      - main

jobs:
  semantic-release:
    name: Semantic
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.repository == 'Life-USTC/server-nextjs' && !contains(github.event.head_commit.message, '[skip ci]')
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup workspace
        uses: ./.github/actions/setup-bun-env

      - name: Run semantic-release
        run: bun run release:semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
